services:
  db:
    image: postgres
    container_name: postgres_db
    env_file: .env
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: